### ISSUE TITLE
Not working on PDS hosted account

### ISSUE THREAD

**Issue by forbin42** [kawamataryo/sky-follower-bridge#101]
Firefox ad-on works fine for bsky.social account but getting invalid handle or password on a PDS hosted account. And yes my handle is valid and verified.

**Comment by kawamataryo** [comment]
If you want to try building on a PDS other than bsky.social, you'll need to build it yourself. Later, I will add instructions on how to do this to the README. For reference, there is something created by [kodxana](https://github.com/kodxana).

https://github.com/kodxana/sky-follower-bridge

**Comment by kawamataryo** [comment]
@forbin42 
Thanks to @kodxana's contributions, it is now available for use with custom PDS as well. Please check the build instructions.

https://github.com/kawamataryo/sky-follower-bridge?tab=readme-ov-file#building-for-custom-pds-servers
