### ISSUE TITLE
Firefox support

### ISSUE THREAD

**Issue by tobozo** [kawamataryo/sky-follower-bridge#11]
hi,

is Firefox support planned for this extension?

**Comment by kawamataryo** [comment]
Thanks for the suggestion.

Some APIs that I am using now in this tool do not work in Firefox; therefore, I had to give up publishing. However, if many users need it, I will try again.

**Comment by tobozo** [comment]
thanks for your feedback 👍 

Bluesky seems to work fine on Firefox so it's probably proportional to the current browser market share.

#### Europe
<img width="1243" alt="image" src="https://github.com/kawamataryo/sky-follower-bridge/assets/1893754/2081cfc2-5328-43ed-acb7-0d28f19cf663">

#### North America
<img width="1216" alt="image" src="https://github.com/kawamataryo/sky-follower-bridge/assets/1893754/025d7e7b-19d9-413d-b600-fb7cec71e6b0">

**Comment by kawamataryo** [comment]
I was surprised to find that Firefox has a surprisingly high share in Europe. In Japan, it is only 3%, very small. I will try to find time to challenge Firefox compatibility again.

![CleanShot 2023-08-25 at 19 28 30](https://github.com/kawamataryo/sky-follower-bridge/assets/11070996/c3fdffd3-a0a7-4fc6-9afc-e0fc17416a60)

**Comment by kawamataryo** [comment]
After checking again with Firefox, it was found that the content_security_policy setting is stricter than Chrome and the current implementation of this tool will not work as is. It seems that all calls to the Bluesky API must be moved to the Service Worker, which is a significant change. It probably will take some time.

https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/content_security_policy

**Comment by tobozo** [comment]
thanks for the insight 👍 

idea: using data from twitter archive instead of accessing the twitter tab could remove some complexity 

<img width="716" alt="image" src="https://github.com/kawamataryo/sky-follower-bridge/assets/1893754/4349e02a-3f88-4194-93f8-0c2cb7bea992">

**Comment by kawamataryo** [comment]
I tried to support Firefox with PR #12.
Can you please help by downloading it from the Firefox Add-ons and confirming that it works?

https://addons.mozilla.org/ja/firefox/addon/sky-follower-bridge/?utm_source=addons.mozilla.org&utm_medium=referral&utm_content=search

**Comment by tobozo** [comment]
wow that was quick!

currently testing and it's working amazingly well 😍

**Comment by tobozo** [comment]
testing complete one my personal account, the plugin worked as expected 👍 

the efficiency is impressive, awesome work, thanks for making this possible!! 🙇

**Comment by kawamataryo** [comment]
@tobozo 
Thank you for testing. It seems to have worked well, so I'm glad😊
