### ISSUE TITLE
[Feature Request] Allow users to create lists from bridge

### ISSUE THREAD

**Issue by dtflowers** [kawamataryo/sky-follower-bridge#110]
**Current Problem:**
Currently we allow `Users` to export their `List Members` from Twitter and then run the `Follow All` action on them in Bridge to import them to Bsky. This is good but a lot of `Users` on Twitter use `Lists` to follow `Users` they wouldn't otherwise follow across segmented topics. This may lead to some cumbersome post-import pain points for `Users` looking to remodel their Twitter `Lists` in Bsky.

**Proposed Solution:**
It would be nice if instead we could also import `List Members` as `Lists` from Bridge. We could add a new action `Create List` that allows `Users` to create a new `List` with that batch. We could then even iterate and allow `Users` to add batches of existing `Lists` if we feel good about this.

Curious how we feel about this? Haven't had a chance to do much more than check the Bsky API docs for feasibility but it seems doable, no? I realize this may be expanding the complexity/scope of the project a bit but wanted to float the idea to get the conversation started as a `List Enjoyer` who could personally get some utility from something like this.

**Comment by kawamataryo** [comment]
I thought it was a really good idea! UI design is a bit challenging, but it is possible to do this. I would like to take on this next challenge.

**Comment by valdotdev** [comment]
Yes, I was wondering about this as well. Just used the extension today though very useful, having to follow creators and artists in the 4 digit range that were already categorized in lists would be a pain to organize all over again.

@kawamataryo Thank you so much for your efforts!

**Comment by dtflowers** [comment]
I threw together an MVP of what we could do here. I don't want to presume that this PR contains the exact behavior we want here but please give it a look and we can hopefully use it as at least a starting point of how to approach this. See [PR](https://github.com/kawamataryo/sky-follower-bridge/pull/112) for details.

**Comment by kawamataryo** [comment]
@dtflowers @valdotdev It has been released! You can use this feature in version 1.4.0.

https://github.com/user-attachments/assets/b5aac6d1-8657-43b9-89cf-0421473d0c54
