### ISSUE TITLE
Blank Screen / Cannot see detected users

### ISSUE THREAD

**Issue by mattpackwood** [kawamataryo/sky-follower-bridge#116]
I "run the tool" and get:

<img width="1588" alt="Screenshot 2024-11-21 at 2 12 05 PM" src="https://github.com/user-attachments/assets/5197e71e-0c0c-40e2-a637-faf2faaad9fa">

When I click on the "button" I get...
<img width="1588" alt="Screenshot 2024-11-21 at 2 12 11 PM" src="https://github.com/user-attachments/assets/ae61f9c0-841a-4a15-826b-20862c66018c">

**Comment by kawamataryo** [comment]
Thank you for the report! This is a first-time occurrence. Are there any errors in the console.log when the black screen appears? If so, please let me know.
