### ISSUE TITLE
Security issue: user credentials stored in local storage

### ISSUE THREAD

**Issue by boxabirds** [kawamataryo/sky-follower-bridge#119]
Username and password are stored in local storage. They shouldn't be. Password at least. 
```
 [STORAGE_KEYS.BSKY_PASSWORD]: password,
```

**Comment by kawamataryo** [comment]
Thank you for your  issue. You are right. I will stop saving passwords in local storage.

**Comment by boxabirds** [comment]
Only thing you need to bear in mind is you may need to store it temporarily
in case for two factor authentication switching tabs results in the
extension being terminated and the username and password being lost! So a
middle ground is that you store them temporarily and be quite explicit
about removing username and password once you’ve got the session token.

**Comment by kawamataryo** [comment]
> So amiddle ground is that you store them temporarily and be quite explicit about removing username and password once you’ve got the session token.

This is a good idea. I think I will implement it.

**Comment by boxabirds** [comment]
Cool! Don’t forget you still need to remove username and password
credentials, even if the user doesn’t need auth token. Ie you also remove
it when sign in is successful.

**Comment by kawamataryo** [comment]
In version 1.4.0, I made a change to stop saving passwords in local storage. However, for convenience, usernames are still saved in local storage as before.

https://github.com/kawamataryo/sky-follower-bridge/pull/123

**Comment by boxabirds** [comment]
Brilliant. How does that work with 2FA? In my testing in the past, I found
that if I switched tabs the extension would terminate so when I went back
to the extension it would reopen but now the context had been lost. I guess
your version if the tab has to be reopened the username field be filled but
the user would have to enter both the password and the auth token correct?

**Comment by kawamataryo** [comment]
@boxabirds When using 2FA, the password is stored in local storage. It is discarded once the 2FA is successful. Therefore, in the case of 2FA, you do not need to re-enter the password even if the tab is closed once.
