### ISSUE TITLE
New version is less functional than previous versions. Stops scanning randomly, and can't resume

### ISSUE THREAD

**Issue by megatrook** [kawamataryo/sky-follower-bridge#130]
On the old version i could see my results immediately, and it would just work even if i went to another tab, however on this new version, it stops randomly, the resume button doesn't work, and i can't see the results immediately, so i can't follow accounts as it is doing its thing. This feels like a massive downgrade to the previous, very simple and functional version. I don't know why this had to be changed, it worked fine! It used to actually go through my entire following list, but now it just stops. It's almost unusable for its purpose

**Comment by kawamataryo** [comment]
Thank you for reporting the issue! This is a bug. We will fix it in the next release.
