### ISSUE TITLE
[Feature request] Request to Show Corresponding Twitter Account for Matches

### ISSUE THREAD

**Issue by JensAltst** [kawamataryo/sky-follower-bridge#132]
I noticed a change in the latest update that has impacted usability. Previously, the add-on displayed the Twitter account and the Bluesky account it thought matched. This was helpful because it provided context (nickname, account name, description, pfp) to confirm whether the suggested match was correct.

In the new update, it appears that only the Bluesky account is shown, without any reference to the Twitter account it corresponds to. This makes it much harder to verify if the match is accurate.

Please add back the functionality to display the corresponding Twitter account alongside the suggested Bluesky account.

If you want to keep it minimalistic, please allow users to toggle the information so it's easier to verify the account.

Cheers.

**Comment by JensAltst** [comment]
Ah FFS I looked but only found similar posts now #77 #115

**Comment by kawamataryo** [comment]
This is new UI.
https://www.youtube.com/watch?v=CnjjfSxm0G0&ab_channel=ryokawamata
