### ISSUE TITLE
Add the Follow All button when importing lists

### ISSUE THREAD

**Issue by valdotdev** [kawamataryo/sky-follower-bridge#138]
Hi! The new import list feature is great but my problem with it is the option to follow the detected users is missing.

I have around 2k members in a list. I need to separately scan those members via the "following" page. So I first scan a list to import then scan again to actually follow which is impractical and inconvenient. Or am I just missing something?

**Comment by kawamataryo** [comment]
I thought that the Follow All button would not be used on the list page, so I hid it. I will fix it to display the Follow All button in the next release.

**Comment by valdotdev** [comment]
Thanks! That would be much appreciated!

**Comment by corkiejp** [comment]
If the list is shorter than 150 accounts, it is possible to convert it to a starter pack which has that option.
https://nws-bot.us/bskyList2StarterPack.php
by : - https://github.com/sbm12/bsky-Pack2List

**Comment by corkiejp** [comment]
Just update the extension, nice feature to follow all on the list. What would be handy is way to remove incorrect matches from the list before hitting the follow all?

**Comment by valdotdev** [comment]
@kawamataryo Thanks! But after testing it out it's not working on mine. After I click on Follow All and pressing OK nothing happens. The pop-up jusr says "Followed 0 users".

I tested this on Vivaldi. I'll try Chrome later once I get home.

![image](https://github.com/user-attachments/assets/c47b0259-0e2b-423e-a8f6-b97bf1e143ad)

**Comment by kawamataryo** [comment]
@valdotdev Sorry! That's a bug! Thank you for your report! I'll fix it today!

**Comment by kawamataryo** [comment]
@corkiejp Thank you! I plan to add a feature to remove false positives in the future!"

**Comment by valdotdev** [comment]
@kawamataryo Thanks for your hard work!

**Comment by kawamataryo** [comment]
@valdotdev 

This issue has been fixed in the v2.1.1 released today! Give it a try!

**Comment by kawamataryo** [comment]
@corkiejp 

This issue has been fixed in the v2.1.1 released today! Give it a try!


https://github.com/user-attachments/assets/32a6f6df-ab19-481c-a9ee-a9696abd57ab

**Comment by valdotdev** [comment]
@kawamataryo Yup looks like everything is working fine! Thanks!

**Comment by corkiejp** [comment]
@kawamataryo Thanks for the tag, will check it out latter today.

**Comment by corkiejp** [comment]
@kawamataryo Sorry for reaching out with this in this issue thread.

I was playing around with my github account and managed to delete my page redirect!
I was successful in resolving that and in the process got my pages deployed from the correct repo
https://github.com/corkiejp/corkiejp.github.io

Want to increase the timing of the redirect but now don't  know how to push the update to the index.html file. So it takes effect on the web. Afraid of messing more up. It has to be something easy to do. I use the web interface and also have the windows desktop app.

What is the easy solution that I am missing.

Thanks in advance for your reply.

**Comment by kawamataryo** [comment]
@corkiejp 

> Just noticed a discrepancy with version numbers and thought the extension wasn't updating?


My previous comment was incorrect. The correct version is v2.2.0, which includes the deletion feature.

**Comment by kawamataryo** [comment]
@corkiejp 

リダイレクトの件については、あなたがどのようなことをしたいのか分かっていないので、私にはアドバイスが難しいです。Redirectのタイミングを遅らせたいのならば、以下のように変更すれば5秒後にリダイレクトされます。

```diff
- <meta http-equiv="refresh" content="0;url=https://bsky.app/profile/corkiejp.github.io">
+ <meta http-equiv="refresh" content="5;url=https://bsky.app/profile/corkiejp.github.io">
```

```diff
- <script>document.location.href = "https://bsky.app/profile/corkiejp.github.io";</script>
+ <script>
+    setTimeout(function() {
+      window.location.href = "https://bsky.app/profile/corkiejp.github.io";
+    }, 5000);
+  </script>

```
