### ISSUE TITLE
Open source logos

### ISSUE THREAD

**Issue by burnettk** [kawamataryo/sky-follower-bridge#139]
Hey, nice logo. 

https://www.sky-follower-bridge.dev/
https://www.spiffworkflow.org/

Appreciate your product!

**Comment by kawamataryo** [comment]
The logo of Sky Follower Bridge is inspired by the icon from Icontify. Therefore, I think there are many similar logos.

![CleanShot 2024-12-10 at 21 41 52@2x](https://github.com/user-attachments/assets/631b5932-6934-4943-a5be-f9c956e51c6e)
