### ISSUE TITLE
Error: Promised response from onMessage listener went out of scope

### ISSUE THREAD

**Issue by HedgeWizardly** [kawamataryo/sky-follower-bridge#14]
Steps to reproduce:

1) Navigate to /following page on twitter
2) Open plugin and enter bsky credentials
3) Click find bluesky owners

Error message appears in extension UI saying:

`Error: Promised response from onMessage listener went out of scope`

Firefox version 116.0.3 (64-bit)

In web developer console:
`Error: Promised response from onMessage listener went out of scope
    ["8x2FD"]< moz-extension://5186f0ef-df24-4408-9465-48bd727672da/static/background/index.js:1
[content.0f79c1f7.js:1:2990](moz-extension://5186f0ef-df24-4408-9465-48bd727672da/content.0f79c1f7.js)
    ["68oK5"]</</< moz-extension://5186f0ef-df24-4408-9465-48bd727672da/content.0f79c1f7.js:1`

**Comment by tobozo** [comment]
hi,

Tried this yesterday on MacOS (Monterey) + Firefox 116.0.3 (64 bits), here are some additional info about my setup:

Browser addons installed and running:
- uBlock Origin
- Stylus
- Privacy Badger
- Firefox Multi Accounts Container
- Sky Follower Bridge

Credentials entered in Sky Follower Bridge:
- email address
- dedicated app password created from BlueSky's settings tab

Browsing conditions:
- Created a container for "Twitter", logged in from there
- Used the same container to log in BlueSky
- Focused on the Twitter tab and clicked on the "Find bluesky users" in Sky Follower Bridge extension icon

Sometimes the query failed, maybe a timeout of glitch on BlueSky API, whenever this happened, the "Find more" button did not appear under the last searched account I had to click the button from the extension icon again. 

Other than that it worked as expected and took between 0.5 and 2 seconds per user. It took a good hour to query about 1500 followers/following users from my account.

I hope this helps you find the cause of the Promise error, I'd start with verifying the credentials (use email addr and app password, not username and certainly not your main bluesky password), then check if a firefox extension is in the way.

**Comment by kawamataryo** [comment]
@tobozo 
Thanks for the information 👍 

@HedgeWizardly 
Thank you for reporting the issue. I need additional information for an investigation. Please let me know what operating system you are using with the extension. Also, does reloading the Twitter page after the error occurs make any difference?

**Comment by kawamataryo** [comment]
I found the cause.
Error handling was incorrect when migrating API calls to Bluesky to Service Worker.

We will fix it in the next release.
