### ISSUE TITLE
"Error: must pass non-empty search query"

### ISSUE THREAD

**Issue by liamjones** [kawamataryo/sky-follower-bridge#15]
I have an unsearchable user. When https://twitter.com/NUae5elll is in a list, SFB returns "Error: must pass non-empty search query"

**Comment by liamjones** [comment]
Also happening with https://twitter.com/mutekyan - is it failing where display name is purely emoji?

**Comment by leonoctem** [comment]
i have the same issue, it's definitely when a username is purely emoji!

**Comment by kawamataryo** [comment]
Thank you for the issue.
This is a bug. I'll fix it.

**Comment by kawamataryo** [comment]
This issue will be fixed in v0.6.3.

**Comment by cassandramckee** [comment]
Thank you, for the update as this issue is affecting me as well :(
