### ISSUE TITLE
English-style linebreaks

### ISSUE THREAD

**Issue by cooljeanius** [kawamataryo/sky-follower-bridge#17]
Currently this extension uses Japanese-style linebreaks: i.e., linebreaks are allowed anywhere, even in the middle of words. It would help make the extension feel more natural to English speakers if English-style linebreaks were implemented instead: that is, linebreaks would only be inserted for line wrapping in between words. Just a minor nitpick; thanks again for this extension!

**Comment by kawamataryo** [comment]
Thank you for the issue. That is certainly true. I'll fix it.

**Comment by kawamataryo** [comment]
@cooljeanius 
This problem has been fixed in v0.6.5. Please wait for its release.
