### ISSUE TITLE
Drop underscores and other invalid values when comparing

### ISSUE THREAD

**Issue by lowercase-donkey** [kawamataryo/sky-follower-bridge#24]
It seems like underscores are not valid for bluesky names, but they are for twitter.

For domains:
> 1. A "name" (Net, Host, Gateway, or Domain name) is a text string up
>    to 24 characters drawn from the alphabet (A-Z), digits (0-9), minus
>    sign (-), and period (.).  Note that periods are only allowed when
>    they serve to delimit components of "domain style names".

For twitter, https://twitter.com/Lowercase_Donkey (note caps, underscore) would have been perfectly fine. However, bluesky is stricter in what it allows for a profile, as they encourage us to use our own domains. lowercasedonkey.bsky.social is the closest I can get.

I don't know if you drop caps already, but it would be nice if it tried to find simple matches based on dropping underscores and such. There can never BE a match to `Lowercase_Donkey`, but maybe the user tried something similar like `lowercasedonkey` or `lowercase-donkey`. Thanks!

**Comment by kawamataryo** [comment]
Thanks for raising the issue!
Right now, the code here absorbs the _ and the case differences. 

https://github.com/kawamataryo/sky-follower-bridge/blob/main/src/lib/domHelpers.ts#L33-L39
https://github.com/kawamataryo/sky-follower-bridge/blob/main/src/lib/bskyHelpers.ts#L10-L53
