### ISSUE TITLE
Extension is now asking read/write permission on all websites?

### ISSUE THREAD

**Issue by u1735067** [kawamataryo/sky-follower-bridge#36]
Hello, 

it seems the latest version(s?) (0.8.0) is now asking read/write permission on all websites, is that expected?
Previously it was only asking for the websites set in https://github.com/kawamataryo/sky-follower-bridge/blob/84a522c8c06442d6110e0bfb7925ab32e84ecfa0/package.json#L52-L57

Best,

**Comment by ShawnBowman** [comment]
Yep I'm seeing this too. The extension got auto-disabled because of it and I'm concerned about turning it back on.

**Comment by kawamataryo** [comment]
I didn't change the permissions...why is that?

https://github.com/kawamataryo/sky-follower-bridge/blob/main/package.json#L53-L57

 I'll look into it.

**Comment by kawamataryo** [comment]
This is the difference in the generated manifest.json from the previous version.

![image](https://github.com/kawamataryo/sky-follower-bridge/assets/11070996/533d3b67-37ff-40ff-8633-8b5f4f82d7ee)

The addition of web_accessible_resources may be the cause of this issue..

**Comment by kawamataryo** [comment]
I will try to fix it so that it does not need unnecessary permissions.

**Comment by kawamataryo** [comment]
I found that either a bug in the build tool or an unnecessary web_accessible_resources permission was introduced and this was the cause of this Issue.

Fixed in the following commit. Not a good way to...

https://github.com/kawamataryo/sky-follower-bridge/commit/2721ee92568bf0b0d19b7433f94649c03c94468c

Unnecessary permissions will no longer be required with the 0.8.1 release.

**Comment by kawamataryo** [comment]
8.1 was released, but not fixed...😢
I will try to fix again.

**Comment by kawamataryo** [comment]
I fixed it again in version 8.2.

**Comment by kawamataryo** [comment]
I fixed it again in version 8.2. 

![image](https://github.com/kawamataryo/sky-follower-bridge/assets/11070996/5076bb2f-1c8b-4582-9a13-09a661457bc9)

**Comment by u1735067** [comment]
Fixed for me, thanks, and thank you for the extension too btw 😊
