### ISSUE TITLE
getting error 403 when trying to fetch

### ISSUE THREAD

**Issue by h3oCharles** [kawamataryo/sky-follower-bridge#53]
![image](https://github.com/user-attachments/assets/c3caea3b-ef14-457f-9aa1-784f64929f10)

im on a locked 🔒 account, not sure what's the cause otherwise

**Comment by rogama25** [comment]
Getthing the same errors. I'm on a public Twitter account, and tried both using my Bluesky password and generating an "app password" for the extension

**Comment by kitia01** [comment]
same errors too

**Comment by xenoplayed** [comment]
I have the same problem. Also disabled temporary 2FA for my bsky account, but problem still persists.

**Comment by kawamataryo** [comment]
Thank you for reporting the issue. It seems that my implementation was flawed, causing excessive load on the server, which led Bluesky to temporarily restrict access to the relevant API. It should be working now. Additionally, this implementation has been fixed in a recent PR:)
