### ISSUE TITLE
Failed To Fetch

### ISSUE THREAD

**Issue by Gremlinton** [kawamataryo/sky-follower-bridge#55]
![image](https://github.com/user-attachments/assets/179d5b55-f158-40ca-86a2-5c5ea1367f44)
![image](https://github.com/user-attachments/assets/97d2a6b7-af39-42fe-a1ea-5c2e88b13dc6)

**Comment by kawamataryo** [comment]
Thank you for reporting the issue. It seems that my implementation was flawed, causing excessive load on the server, which led Bluesky to temporarily restrict access to the relevant API. It should be working now. Additionally, this implementation has been fixed in a recent PR:)
