### ISSUE TITLE
Doesn't find any matches on Firefox; just throws an error with every search attempt.

### ISSUE THREAD

**Issue by TiZ-HugLife** [kawamataryo/sky-follower-bridge#56]
The extension is no longer finding any users. Every search attempt creates this message in the console:

Error: TypeError: NetworkError when attempting to fetch resource.
    searchUser moz-extension://d40cb71c-b65e-4bd0-8d07-7ad13506afca/content.0f79c1f7.js:1
content.0f79c1f7.js:1:5807

Would I be correct in presuming that recent commits are in an attempt to address this?

Thanks for your work on this great tool. 🙂

**Comment by kawamataryo** [comment]
Thank you for reporting the issue. It seems that my implementation was flawed, causing excessive load on the server, which led Bluesky to temporarily restrict access to the relevant API. It should be working now. Additionally, this implementation has been fixed in a recent PR:)

**Comment by cooljeanius** [comment]
Seems to work properly for me now with Firefox 132 on macOS Big Sur; this can probably be closed

**Comment by TiZ-HugLife** [comment]
Confirming it works for me again. Thank you!
