### ISSUE TITLE
Follow all bluesky accounts found in one click

### ISSUE THREAD

**Issue by drkying** [kawamataryo/sky-follower-bridge#73]
When you have finished retrieving the bluesky account, press f12 and switch to the console tab; copy the following content and execute it to follow all accounts.

const shadowRoot = document.querySelector("html > plasmo-csui").shadowRoot;
const buttons = shadowRoot.querySelectorAll('.card-actions button');

let index = 0;
const interval = setInterval(() => {
    const button = buttons[index];
    if (button && button.textContent.trim() === 'Follow on Bluesky') {
        button.click();
    }
    index++;
    if (index >= buttons.length) {
        clearInterval(interval);
    }
}, 100);

**Comment by kawamataryo** [comment]
Thank you for the workaround. We have added the "Follow All" feature in v1.0.0. If you have access to v1.0.0, please try it out using this button.

![CleanShot 2024-11-07 at 20 10 13@2x](https://github.com/user-attachments/assets/11b3b673-bade-49b8-a9da-38260f9e32d9)

**Comment by John-Enigma** [comment]
> Thank you for the workaround. We have added the "Follow All" feature in v1.0.0. If you have access to v1.0.0, please try it out using this button.
> 
> ![CleanShot 2024-11-07 at 20 10 13@2x](https://private-user-images.githubusercontent.com/11070996/383932977-11b3b673-bade-49b8-a9da-38260f9e32d9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzExMDE5OTEsIm5iZiI6MTczMTEwMTY5MSwicGF0aCI6Ii8xMTA3MDk5Ni8zODM5MzI5NzctMTFiM2I2NzMtYmFkZS00OWI4LWE5ZGEtMzgyNjBmOWUzMmQ5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA4VDIxMzQ1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU4ZTAxZDkyNWEwYjQ4NjI2MzQ4ZTNjNzdmYmQ1NmZlNDI2Mzc0ZTljMjFlOWY1MTcxY2VjM2Q0MTM2MDVkMTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.SfWu_5cL31McebVPWSMI_0tD2pE0ZV_cor2vQ5-YQYQ)

This update is not available on Firefox.

**Comment by jo-chemla** [comment]
Great to see that `Follow all` feature! 

Latest addon released on the firefox [addon page](https://addons.mozilla.org/fr/firefox/addon/sky-follower-bridge/) is v0.7.2 instead of 1.x and there are not built extensions (xpi & co) in github releases. Could be useful to add addon releases as github releases as well!
