### ISSUE TITLE
Stuck on "Processing"

### ISSUE THREAD

**Issue by prouss1** [kawamataryo/sky-follower-bridge#79]
I appreciate the simplicity of this extension, thanks.  But while it found the people I follow and I clicked to import them all, it's been stuck for a couple of hours with the grey "processing" button.  Is this normal for how long the process can take?  I only have 170 or so names.

Follow-up:  I gave up on the first attempt after a few hours, then went back to X and scanned again.  This time it found only 7 names and quickly processed them (I could see the names being accepted one by one).  But the other 160 or so are still not processed and now the extension seems unable to find them.  Any suggestions?

**Comment by kawamataryo** [comment]
Thank you for the issue. What browser are you using? and What kind of screen is it? If you could provide a screenshot, it might help us resolve the issue.

**Comment by prouss1** [comment]
Thanks for getting back to me.  In the end I got it to work on the full list of names with some combo of quitting both Chrome and X and rebooting, I can't remember which in particular did the trick.  But then it accepted all 170 or so names quite quickly.  So again, great extension, saved a lot of time!

**Comment by kawamataryo** [comment]
I'm glad to hear that!
