### ISSUE TITLE
Match bluesky handles in twitter description

### ISSUE THREAD

**Issue by saurabhdaware** [kawamataryo/sky-follower-bridge#82]
Currently the algorithm matches if someone has X handle in bluesky's description but would be nice if we could match bsky handles in twitter description.

So if I have twitter description like this-

<img width="411" alt="image" src="https://github.com/user-attachments/assets/59717eee-234d-4f77-8929-ea3e1c8616dd">

Maybe we can match them with bsky profile

**Comment by choco-latin** [comment]
I think this is how most people believe that they can be found automatically.

I would also had that the algorithm should parse as well the links of the form `https://bsky.app/profile/username.bsky.social` which a lot of people put in ther description instead of the `@username`

**Comment by kawamataryo** [comment]
@saurabhdaware @choco-latin 

I have fixed this in the Chrome version v1.0.6. If the bio on X contains the string xxx.bsky.social or https://bsky.app/profile/xxx.xxx, the logic now prioritizes those.
