### ISSUE TITLE
Lists not loading properly

### ISSUE THREAD

**Issue by BeardyThings** [kawamataryo/sky-follower-bridge#83]
When I load one of my list's members, using the "x.com/i/lists/<list_id>/members" url, or by going to the list, clicking Manage, clicking Members, or by just clicking "Manage Members" from the list's page, the Bridge app will load the first page just fine, but then it will start scrolling the background Twitter/X page, and *not* the List in the foreground of the window, which is causing the App to load users that are being reshared onto that timeline, and not the people that have been added to the list.  Restarting Chrome, updating the Bridge app, and restarting my computer do not fix this issue.  This occurs with all lists I attempt.

**Comment by kawamataryo** [comment]
Thank you for the report! This is a bug in the scrolling logic. I would like to fix it.

**Comment by fredericrous** [comment]
I'm getting the same issue. I'm on osx 15.1. chrome 130.0.6723.117
