### ISSUE TITLE
multiple copies of spurious users show up in my results

### ISSUE THREAD

**Issue by kevinmarks** [kawamataryo/sky-follower-bridge#89]
I'm not sure why @handle.invalid is there as a username or why I get several groups of these in the list of found users

<img width="1050" alt="Screenshot 2024-11-12 at 05 09 22+0000" src="https://github.com/user-attachments/assets/c7fa1676-7c13-4a41-ac91-e60e48989cde">
<img width="1040" alt="Screenshot 2024-11-12 at 05 08 53+0000" src="https://github.com/user-attachments/assets/7a78fc6d-788d-4ea3-9dd0-a311d2e49ef3">

**Comment by kawamataryo** [comment]
This is a bug. We'll fix it in the next release.

**Comment by kawamataryo** [comment]
Can you tell me the URL of which page you scanned to verify the operation?
