### ISSUE TITLE
Invalid identifier or password

### ISSUE THREAD

**Issue by kcornishscott** [kawamataryo/sky-follower-bridge#90]
Keep getting this message. I know my user name and password are correct because I used them to log in to an incognito window and they worked just fine. I have tried using my username and also my email address. Both pop up that message.

**Comment by kcornishscott** [comment]
Chrome.

Here is a screenshot:
[image: image.png]

**Comment by kawamataryo** [comment]
screenshot is not displayed.

**Comment by kcornishscott** [comment]
I cut and pasted it into the body of the email.... I guess I can try
attaching it.

**Comment by kawamataryo** [comment]
I wonder why. I'm not receiving the email. Could you paste it directly into this issue?

**Comment by kcornishscott** [comment]
it seems like your email provider is stripping images and attachments. I
can try pasting into the comment yes.

**Comment by kcornishscott** [comment]
![Screenshot (54)](https://github.com/user-attachments/assets/4a8a1c1a-92e5-4bdb-9da8-0d44b7879e5e)

**Comment by kawamataryo** [comment]
Thank you for sharing! I noticed that the handle name doesn’t have a domain. What happens if you add a domain name? For example, `your_identifier.bsky.social` .

Please check the contents of this document.

https://www.sky-follower-bridge.dev/troubleshooting.html

**Comment by kcornishscott** [comment]
THANK YOU! Fixed and working great now, my brain just couldn't brain.  :-)
