### ISSUE TITLE
Feature Request: Block user button

### ISSUE THREAD

**Issue by johnpdowling** [kawamataryo/sky-follower-bridge#91]
In addition to "Follow User.." it would be useful to have a "Block User.." button/option in order to migrate block lists from one platform to the other. Thanks!

**Comment by kawamataryo** [comment]
Thank you for the feature request! There is already a Block button, but is this a different feature?

You can detect blocked users by running Follower Bridge at the following URL.

https://x.com/settings/blocked/all

![CleanShot 2024-11-14 at 15 30 24@2x](https://github.com/user-attachments/assets/9993a46e-42d8-4d04-8fa8-df0ecaa4c0a7)

**Comment by johnpdowling** [comment]
Great news! I must have been looking at an old demo, I'll close the ticket. Thanks for all that you do!
