### ISSUE TITLE
cannot get sky follower to work

### ISSUE THREAD

**Issue by snafulives** [kawamataryo/sky-follower-bridge#92]
Invalid identifier or password

This is what I keep getting. I mean for two days, 7 videos, and 40 attempts. 
I have the extention.
I go to X profile and to those accounts I am following
I hit Alt B and get skybridge
I put in skybridge handle exactly as told  @8morelives.bsky.social
I put make a password from the password app, copy it and put it in

I get that message.
I try again. 
Can you help?

**Comment by snafulives** [comment]
I also tried with a different handle of @snafulives

**Comment by kawamataryo** [comment]
Thank you for your question! If you could send me a screenshot of the error screen, it might help me assist you better.

**Comment by snafulives** [comment]
Does this help?

**Comment by snafulives** [comment]
![Screenshot (76)](https://github.com/user-attachments/assets/d6f189cb-cc7e-434c-8b12-c940d39cdad1)

**Comment by kawamataryo** [comment]
I understand the problem. There are too many @ symbols.
You should enter the ID `@8morelives.bsky.social`.
