### ISSUE TITLE
Both Follow All and Follow on Bluesky buttons hang on Processing

### ISSUE THREAD

**Issue by livy-lgtm** [kawamataryo/sky-follower-bridge#95]
I've successfully gotten my list of matched accounts but both Follow All and Follow on Bluesky buttons hang on "Processing" and don't actually add any followers to my account. I've refreshed and tried again multiple times but it hangs every time and no followers are added on my bluesky account 
<img width="1159" alt="image" src="https://github.com/user-attachments/assets/8337e593-c457-4650-b120-67fdb3727253">

**Comment by kawamataryo** [comment]
I'll look into it!

**Comment by kawamataryo** [comment]
The increase in users has caused Bluesky's servers to struggle, and it seems that the Bluesky API is not functioning properly. It might start working again after a while.
